### ISSUE TITLE
Is it possible to accept/import a selected LSP completion when using `<c-y>` in the pmenu?

### ISSUE THREAD

**Issue by riskygit** [girishji/vimcomplete#37] opened 2024-03-12 01:09 UTC
Hi, there. When a list of completions appears, I can move the selection with `<c-n>` and `<c-p>`, but when I press `<c-y>`, it just refreshes the completion query (the list is re-built using the selected item). It would be nice if I could set `<c-y>` on an LSP item to insert the completion, close the popup, and even import the item... is this something vimcomplete is concerned with or should I inquire in the LSP repo?

**Comment by girishji** [comment] 2024-03-12 04:47
from `:h popupmenu-keys`

```
In all three states these can be used:
CTRL-Y		  Yes: Accept the currently selected match and stop completion.
```

Is it not working correctly? Or you want it to do more? Importing items automatically is already possible (at least in jdtls) in yegappan LSP (you have to set it up, see their wiki).

**Comment by riskygit** [comment] 2024-03-13 18:18
Yes, that fixed it. How did you get auto-import working? I tried with TypeScript, but `<c-y>` on something that should be imported still requires me to look through the code actions.

Probably unrelated, but in Rust, I can't seem to get completions for anything that isn't fully qualified. For example,

```rust
let x: Clie
```

where `reqwest::blocking::Client` is available (and even used in fully qualified form elsewhere in the document) doesn't suggest `Client` (`reqwest::blocking::Client`) not does selecting _any_ of the options import anything. Completions are a bit useless for Rust right now.

**Comment by girishji** [comment] 2024-03-13 19:06
I got it working for jdtls, and I had to add this:

```
## Make jdtls 'code actions' do 'organize imports', 'add unimplemented methods', etc.,
var jfname = $'{$HOME}/.vim/plugged/lsp/autoload/lsp/textedit.vim'
if filereadable(jfname) && exists("g:loaded_lsp")
    import jfname
    def g:JavaWorkspaceEdit(cmd: dict<any>)
        for editAct in cmd.arguments
            textedit.ApplyWorkspaceEdit(editAct)
        endfor
    enddef
    g:LspRegisterCmdHandler('java.apply.workspaceEdit', g:JavaWorkspaceEdit)
end
```

Can you check the 'wiki' tab on yegappan lsp for instructions on rust? I could look into it if it already works in Lsp.   Can you also disable this plugin and try autocompletion lsp directly, and check if auto import works?

**Comment by girishji** [comment] 2024-03-13 19:11
Here is the relevant code from LSP client: https://github.com/yegappan/lsp/blob/9111948aa541df98c66da57ab34e3f9914f44d01/autoload/lsp/completion.vim#L603

**Comment by girishji** [comment] 2024-03-13 19:23
> where reqwest::blocking::Client is available (and even used in fully qualified form elsewhere in the document) doesn't suggest Client

it is possible rust server is not sending completions because of configuration issue. you can enable logging for yegappan lsp client (see their doc). it prints out messages from server.

**Comment by riskygit** [comment] 2024-03-13 20:31
You're probably right about the Rust config requiring some extra work, but here are two videos with TypeScript. The first uses LSP-only completion (`<c-y>` inserts imports). The second uses vimcomplete... there appears to be duplicates and none of them import upon completion. I think there's an option to disable duplicates in the LSP config, though, so I'll probably need to enable that.

https://github.com/girishji/vimcomplete/assets/105889909/9beeaae1-0976-4a09-89df-7a050651b940


https://github.com/girishji/vimcomplete/assets/105889909/1bb2afde-fb76-4cdb-8814-3deb86065275

**Comment by riskygit** [comment] 2024-03-13 20:50
(Also, what is that `Lazy doc` thing? Should there be information there?)

**Comment by riskygit** [comment] 2024-03-13 22:05
Perhaps this is related... https://github.com/girishji/vimcomplete/blob/main/autoload/vimcomplete/lsp.vim#L18

**Comment by girishji** [comment] 2024-03-13 22:40
> (Also, what is that `Lazy doc` thing? Should there be information there? It seems to work without vimcomplete, but not with it.)

I submitted a PR earlier today. It is a bug in yegappan lsp. It's too late for me now (EU time). Have to look into other issues later.

**Comment by girishji** [comment] 2024-03-14 17:58
Which language server are you using? can you share the config?

**Comment by riskygit** [comment] 2024-03-14 18:22
```vim
g:LspOptionsSet({
  completionMatcher: 'fuzzy',
  diagVirtualTextAlign: 'after',
  ignoreMissingServer: true,
  showDiagWithVirtualText: true,
})

g:VimCompleteOptionsSet({
  completor: {
    recency: false,
    kindDisplayType: 'symbol',
  },
  buffer: {
    searchOtherBuffers: false,
  },
  lsp: {
    maxCount: 100,
    priority: 20,
  },
  vsnip: {
    enable: true,
    adaptNonKeyword: true,
  },
  vimscript: {
    enable: true,
    priority: 15,
  },
})

g:LspAddServer([{
  name: 'typescript-language-server',
  filetype: ['javascript', 'typescript'],
  path: 'typescript-language-server',
  args: ['--stdio'],
  rootSearch: ['tsconfig.json', 'package.json', 'jsconfig.json', '.git'],
}])
```

https://github.com/typescript-language-server/typescript-language-server

**Comment by girishji** [comment] 2024-03-14 18:32
With only yegappan lsp I am not seeing all the completions:

<img width="526" alt="Screenshot 2024-03-14 at 7 32 44 PM" src="https://github.com/girishji/vimcomplete/assets/16529248/ada9fc1e-1a4f-4542-948e-ee9ce8bc8818">

**Comment by riskygit** [comment] 2024-03-14 18:52
Sorry, `Readable` is from something I have in my `package.json`. I thought you meant the relevant vim configuration. Without the package (https://github.com/anthropics/anthropic-sdk-typescript) you won't see that item. When you add vimcomplete, do you get duplicates and broken auto-import?

**Comment by girishji** [comment] 2024-03-14 18:53
> Perhaps this is related to the autoimport issue... https://github.com/girishji/vimcomplete/blob/main/autoload/vimcomplete/lsp.vim#L18
> 
> I see in the docs that should be disabled only if vimcomplete is going to take care of the text edits.

`completionTextEdit` is related to snippet engine. vssnip takes care of snippet completion, including snippets supplied by LSP.

**Comment by girishji** [comment] 2024-03-14 18:55
Can you provide another example where auto-import happens for you, without additional packages? I'd like to reproduce it on my end.

**Comment by girishji** [comment] 2024-03-14 18:56
OK, I reproduced it after installing anthropic. I will look into this.

**Comment by girishji** [comment] 2024-03-15 13:34
It should be fixed by now. it was not applying text edits correctly since vssnip is very selective. with this change lsp client will apply text edits for lsp server originated user-edits, and there is no interference b/w lsp client and vssnip even though both subscribe to CompleteDone event.

**Comment by riskygit** [comment] 2024-03-15 14:11
Hmm... doesn't seem to be working for me. I do have vsnip; do I need to change some other configuration setting?

**Comment by girishji** [comment] 2024-03-15 16:44
Let me check.

**Comment by girishji** [comment] 2024-03-15 16:49
works for me https://asciinema.org/a/hRSoV67kMRHg5YzxnhLgrVIWV

**Comment by riskygit** [comment] 2024-03-15 16:58
Yes, it is working! I just updated LSP (he merged your PR). One more thing: when I use `<c-n>` to scroll options, it shows the box to the right with information now, but when I use `<c-p>` to scroll back up, it says "Lazy doc." Do you see that, too?

**Comment by girishji** [comment] 2024-03-15 19:57
It is a Vim bug. Maybe a 9.1 regression. I filed a report:

https://github.com/vim/vim/issues/14204

**Comment by riskygit** [comment] 2024-03-15 20:02
Interesting; thanks for that! Hope it gets fixed. I took a look at https://github.com/vim/vim/commits/b4b3d7de2413bf277445ea724c9cbd5e6bf9a334/src/insexpand.c to see if anything stood out, but I'm a bit out of my element here, unfortunately.

**Comment by girishji** [comment] 2024-03-15 20:09
I don't have bandwidth unfortunately. I posted on yegappan lsp. He contributes to Vim. Maybe he'll look into it.

**Closed** 2024-03-15 20:12 UTC

**Comment by girishji** [comment] 2024-03-19 13:19
Should be fixed by my PR https://github.com/vim/vim/pull/14231
