### ISSUE TITLE
How can I do preselect candidate

### ISSUE THREAD

**Issue by ydzhou** [girishji/vimcomplete#43] opened 2024-03-21 08:51 UTC
I want the first candidate to be selected and (even better) filled in.

For example, I typed "he", and my first candidate is "hello". I would like to see hello being selected. And I can just type <CR> to complete.

**Comment by girishji** [comment] 2024-03-21 15:59
Try now. Added `noinsert` and `noselect`. see readme.

**Comment by ydzhou** [comment] 2024-03-21 20:08
It works! Thanks

**Comment by ydzhou** [comment] 2024-03-22 19:51
Couple usability issue

When both noselect and noinsert set to false, it will autopopulate the first candidate and I cannot type any more. For example, if I type `c`, I get first candidate `cat` populated, and I can only type after `cat`. If I actually look for `cup`, I cannot type `u` after `c`.

When only noselect set to false, it only select first candidate. If I cycle through my candidate using tab, I cannot autofill the first candidate

**Comment by ydzhou** [comment] 2024-03-22 19:52
@girishji here

**Comment by ydzhou** [comment] 2024-03-22 19:53
https://github.com/girishji/vimcomplete/assets/3310714/33f71efe-b340-40d4-97df-ddbf6b7d7d7c

**Comment by ydzhou** [comment] 2024-03-22 19:54
https://github.com/girishji/vimcomplete/assets/3310714/72ec4e9e-f1d2-42b2-810b-e6e8edefd337

**Comment by girishji** [comment] 2024-03-22 19:58
It is expected, because autocmd opens popup and blocks you from typing. I'll think about a solution.

**Comment by ydzhou** [comment] 2024-03-22 20:22
tbh I am fine with noinsert not working as expect... I think my major UX blocker is that if I cycle through tab, I cannot fill in the first candidate without press ENTER as I shown in my first screenshot...

**Comment by girishji** [comment] 2024-03-22 20:34
> When only noselect set to false, it only select first candidate. If I cycle through my candidate using tab, I cannot autofill the first candidate

This is working as expected. You can verify by disabling this plugin and use `<c-x><c-n>`. See `:h 'completeopt'`.

The other case (when both are false) is an issue. I will work on this tomorrow.

**Comment by girishji** [comment] 2024-03-23 07:10
Should work now. set `preselect = true`

**Comment by ydzhou** [comment] 2024-03-24 01:02
Thanks for the quick update.

Few things I notice acting differently
1. if candidate has space, it will only fill in the first part before the space if I press TAB or <C-n>
2. I set noNewLine and I select the candidate and press ENTER, the candidate popup will still be there. I expect if I confirm my selection, the pop up will disapear.

**Comment by girishji** [comment] 2024-03-24 06:46
#2 should be fixed. couldn't reproduce #1 but I have added a option `debug` to the `completor`. can you do `:messages` and compare `abbr` and `word` for the element with space, after doing completion?

**Comment by ydzhou** [comment] 2024-03-24 20:48
```
[{'word': 'package', 'info': '', 'user_data': {'label': 'package pine_test', 'textEdit': {'range': {'end': {'character': 0, 'line': 1}, 'start': {'cha
racter': 0, 'line': 0}}, 'newText': 'package pine_test'}, 'sortText': '00001', 'kind': 9, 'insertTextFormat': 2, 'documentation': {'kind': 'markdown',
 'value': ''}, 'filterText': 'package pine_test'}, 'menu': '[lsp]', 'score': '00001', 'kind': 'M Module', 'abbr': 'package pine_test', 'dup': 1}, {'wo
rd': 'package', 'info': '', 'user_data': {'label': 'package pine', 'textEdit': {'range': {'end': {'character': 0, 'line': 1}, 'start': {'character': 0
, 'line': 0}}, 'newText': 'package pine'}, 'preselect': true, 'sortText': '00000', 'kind': 9, 'insertTextFormat': 2, 'documentation': {'kind': 'markdo
wn', 'value': ''}, 'filterText': 'package pine'}, 'menu': '[lsp]', 'score': '00000', 'kind': 'M Module', 'abbr': 'package pine', 'dup': 1}, {'word': '
package', 'info': '', 'user_data': {'label': 'package internal', 'textEdit': {'range': {'end': {'character': 0, 'line': 1}, 'start': {'character': 0,
'line': 0}}, 'newText': 'package internal'}, 'sortText': '00002', 'kind': 9, 'insertTextFormat': 2, 'documentation': {'kind': 'markdown', 'value': ''}
, 'filterText': 'package internal'}, 'menu': '[lsp]', 'score': '00002', 'kind': 'M Module', 'abbr': 'package internal', 'dup': 1}, {'word': 'package',
 'info': '', 'user_data': {'label': 'package internal_test', 'textEdit': {'range': {'end': {'character': 0, 'line': 1}, 'start': {'character': 0, 'lin
e': 0}}, 'newText': 'package internal_test'}, 'sortText': '00003', 'kind': 9, 'insertTextFormat': 2, 'documentation': {'kind': 'markdown', 'value': ''
}, 'filterText': 'package internal_test'}, 'menu': '[lsp]', 'score': '00003', 'kind': 'M Module', 'abbr': 'package internal_test', 'dup': 1}, {'word':
 'package', 'info': '', 'user_data': {'label': 'package main', 'textEdit': {'range': {'end': {'character': 0, 'line': 1}, 'start': {'character': 0, 'l
ine': 0}}, 'newText': 'package main'}, 'sortText': '00004', 'kind': 9, 'insertTextFormat': 2, 'documentation': {'kind': 'markdown', 'value': ''}, 'fil
terText': 'package main'}, 'menu': '[lsp]', 'score': '00004', 'kind': 'M Module', 'abbr': 'package main', 'dup': 1}]
[{'word': 'package', 'info': '', 'user_data': {'label': 'package internal', 'textEdit': {'range': {'end': {'character': 0, 'line': 1}, 'start': {'char
acter': 0, 'line': 0}}, 'newText': 'package internal'}, 'sortText': '00002', 'kind': 9, 'insertTextFormat': 2, 'documentation': {'kind': 'markdown', '
value': ''}, 'filterText': 'package internal'}, 'menu': '[lsp]', 'score': '00002', 'kind': 'M Module', 'abbr': 'package internal', 'dup': 1}, {'word':
 'package', 'info': '', 'user_data': {'label': 'package pine_test', 'textEdit': {'range': {'end': {'character': 0, 'line': 1}, 'start': {'character':
0, 'line': 0}}, 'newText': 'package pine_test'}, 'sortText': '00001', 'kind': 9, 'insertTextFormat': 2, 'documentation': {'kind': 'markdown', 'value':
 ''}, 'filterText': 'package pine_test'}, 'menu': '[lsp]', 'score': '00001', 'kind': 'M Module', 'abbr': 'package pine_test', 'dup': 1}, {'word': 'pac
kage', 'info': '', 'user_data': {'label': 'package pine', 'textEdit': {'range': {'end': {'character': 0, 'line': 1}, 'start': {'character': 0, 'line':
 0}}, 'newText': 'package pine'}, 'preselect': true, 'sortText': '00000', 'kind': 9, 'insertTextFormat': 2, 'documentation': {'kind': 'markdown', 'val
ue': ''}, 'filterText': 'package pine'}, 'menu': '[lsp]', 'score': '00000', 'kind': 'M Module', 'abbr': 'package pine', 'dup': 1}, {'word': 'package',
 'info': '', 'user_data': {'label': 'package internal_test', 'textEdit': {'range': {'end': {'character': 0, 'line': 1}, 'start': {'character': 0, 'lin
e': 0}}, 'newText': 'package internal_test'}, 'sortText': '00003', 'kind': 9, 'insertTextFormat': 2, 'documentation': {'kind': 'markdown', 'value': ''
}, 'filterText': 'package internal_test'}, 'menu': '[lsp]', 'score': '00003', 'kind': 'M Module', 'abbr': 'package internal_test', 'dup': 1}, {'word':
 'package', 'info': '', 'user_data': {'label': 'package main', 'textEdit': {'range': {'end': {'character': 0, 'line': 1}, 'start': {'character': 0, 'l
ine': 0}}, 'newText': 'package main'}, 'sortText': '00004', 'kind': 9, 'insertTextFormat': 2, 'documentation': {'kind': 'markdown', 'value': ''}, 'fil
terText': 'package main'}, 'menu': '[lsp]', 'score': '00004', 'kind': 'M Module', 'abbr': 'package main', 'dup': 1}]   
```

**Comment by ydzhou** [comment] 2024-03-24 20:50
https://github.com/girishji/vimcomplete/assets/3310714/233b0ac9-dc51-48b1-b5f0-357de8f4ee5f

**Comment by ydzhou** [comment] 2024-03-24 20:58
You can reproduce by create a new Golang program. And use gopls to autocomplete `package {your package name}`

**Comment by girishji** [comment] 2024-03-24 21:15
The bug is in LSP. Vim ins-complete protocol says `word` should contain completion candidate. But we have `word': 'package'`, which is what gets completed. However,  `user_data` has the required info: `'user_data': {'label': 'package pine_test'`. Lsp should put `package` in `abbr` and `package pine_test` in `word`. I will look into this.

**Comment by girishji** [comment] 2024-03-25 06:57
The mismatch between what you see in the menu and what gets completed is a consequence of how `gopls` works. 'gopls' is not aware of the 'preselect' feature. It appears that 'preselect' feature is not compatible (not a use case) for LSP. If you type <space> for instance, it will complete 'package pine_test'. It will be the same behavior if you use yegappan lsp directly. The word 'pine_test' is actually inserted post completion, by modifying the buffer directly through 'textEdit' mechanism of Lsp client.

Generally speaking, Lsp servers send their completion text in the 'label' field (see doc below). In this case, it is WYSIWYG. 'gopls' is sending completion text ('package') in 'insertText' (see doc below). Lsp client copies this into Vim's 'word' which is what gets completed. 'gopls' is also sending 'label' where it places 'package pine_test'. This is copied into Vim's 'abbr' which is what gets displayed. They do not match. Only when you finish completion (dismiss popup menu) will they match.

I am afraid not much can be done in this plugin. 'preselect'-ing is not a use-case of LSP. yegappan lsp could copy 'label' into Vim's 'word' even when 'insertText' is present, but this will break the invariants. It may also break snippet completion.
 

```
	/**
	 * A human-readable string describing the actual change. The string
	 * is rendered prominent in the user interface.
	 */
	label: string
	
	/**
	 * The label of this completion item.
	 *
	 * The label property is also by default the text that
	 * is inserted when selecting this completion.
	 *
	 * If label details are provided the label itself should
	 * be an unqualified name of the completion item.
	 */
	label: string;

```

```
	/**
	 * A string that should be inserted into a document when selecting
	 * this completion. When omitted the label is used as the insert text
	 * for this item.
	 *
	 * The `insertText` is subject to interpretation by the client side.
	 * Some tools might not take the string literally. For example
	 * VS Code when code complete is requested in this example
	 * `con<cursor position>` and a completion item with an `insertText` of
	 * `console` is provided it will only insert `sole`. Therefore it is
	 * recommended to use `textEdit` instead since it avoids additional client
	 * side interpretation.
	 */
	insertText?: string;

```

'textEdit' gets copied into Vim's 'user_data', and it specifies the region to modify, and how.

```
	/**
	 * An edit which is applied to a document when selecting this completion.
	 * When an edit is provided the value of `insertText` is ignored.
	 * ...
        textEdit;
*/

```

**Comment by ydzhou** [comment] 2024-03-25 21:11
Make sense. I think I am OK with not having pre-selected.

**Closed** 2024-03-26 06:37 UTC
